version: "3.8"
services :
  mysql:
    container_name: mysql
    image: mysql
    ports :
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "thoughts"
    volumes: 
      - mysql-data:/var/lib/mysql
      - ./message.sql:/docker-entrypoint-initdb.d/message.sql
    networks: 
      - two-tier
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
  
  flask-app:
    build:
      context: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_USER: "root" 
      MYSQL_PASSWORD: "root"
      MYSQL_DB: "thoughts"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - two-tier
    restart: always
    

volumes:
  mysql-data:

networks:
  two-tier: 

